# Generated by Django 3.2.25 on 2024-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_no', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
