# Generated by Django 3.2.25 on 2024-06-14 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_no', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parenttitle')),
            ],
        ),
    ]
