# Generated by Django 3.2.25 on 2024-06-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_no', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subtitle')),
            ],
        ),
    ]
