# Generated by Django 3.2.25 on 2024-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadfilelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilelist',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
