# Generated by Django 3.2.25 on 2024-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadfilelist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilelist',
            name='key',
            field=models.CharField(default='0.0', max_length=255),
        ),
    ]
