# Generated by Django 3.2.25 on 2024-06-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_uploadfilelist_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childtitle',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='uploadfilelist',
            name='child_id',
        ),
        migrations.AddField(
            model_name='childtitle',
            name='sub_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childtitles', to='myapp.subtitle'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='myapp.parenttitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfilelist',
            name='child',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfiles', to='myapp.childtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfilelist',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddConstraint(
            model_name='childtitle',
            constraint=models.UniqueConstraint(fields=('sub_title', 'child_no'), name='unique_childtitle'),
        ),
        migrations.AddConstraint(
            model_name='parenttitle',
            constraint=models.UniqueConstraint(fields=('parent_no',), name='unique_parent_no'),
        ),
        migrations.AddConstraint(
            model_name='subtitle',
            constraint=models.UniqueConstraint(fields=('parent', 'sub_no'), name='unique_subtitle'),
        ),
    ]
