# Generated by Django 3.2.25 on 2024-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240619_0932'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parenttitle',
            name='unique_parent_no',
        ),
        migrations.RemoveConstraint(
            model_name='subtitle',
            name='unique_subtitle',
        ),
        migrations.RenameField(
            model_name='subtitle',
            old_name='parent',
            new_name='parent_title',
        ),
        migrations.AlterField(
            model_name='parenttitle',
            name='parent_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='subtitle',
            constraint=models.UniqueConstraint(fields=('parent_title', 'sub_no'), name='unique_subtitle'),
        ),
    ]
